version: '3.1'
services:
  db:
    image: mysql:5
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "spring"
      # MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
